REM INSERTING into BH103436.ESTADO
SET DEFINE OFF;
Insert into BH103436.ESTADO (UF,NOME) values ('AC','Acre');
Insert into BH103436.ESTADO (UF,NOME) values ('AL','Alagoas');
Insert into BH103436.ESTADO (UF,NOME) values ('AP','Amapá');
Insert into BH103436.ESTADO (UF,NOME) values ('AM','Amazonas');
Insert into BH103436.ESTADO (UF,NOME) values ('BA','Bahia');
Insert into BH103436.ESTADO (UF,NOME) values ('CE','Ceará');
Insert into BH103436.ESTADO (UF,NOME) values ('DF','Distrito Federal');
Insert into BH103436.ESTADO (UF,NOME) values ('ES','Espírito Santo');
Insert into BH103436.ESTADO (UF,NOME) values ('GO','Goiás');
Insert into BH103436.ESTADO (UF,NOME) values ('MA','Maranhão');
Insert into BH103436.ESTADO (UF,NOME) values ('MT','Mato Grosso');
Insert into BH103436.ESTADO (UF,NOME) values ('MS','Mato Grosso do Sul');
Insert into BH103436.ESTADO (UF,NOME) values ('MG','Minas Gerais');
Insert into BH103436.ESTADO (UF,NOME) values ('PA','Pará');
Insert into BH103436.ESTADO (UF,NOME) values ('PB','Paraíba');
Insert into BH103436.ESTADO (UF,NOME) values ('PR','Paraná');
Insert into BH103436.ESTADO (UF,NOME) values ('PE','Pernambuco');
Insert into BH103436.ESTADO (UF,NOME) values ('PI','Piauí');
Insert into BH103436.ESTADO (UF,NOME) values ('RJ','Rio de Janeiro');
Insert into BH103436.ESTADO (UF,NOME) values ('RN','Rio Grande do Norte');
Insert into BH103436.ESTADO (UF,NOME) values ('RS','Rio Grande do Sul');
Insert into BH103436.ESTADO (UF,NOME) values ('RO','Rondônia');
Insert into BH103436.ESTADO (UF,NOME) values ('RR','Roraima');
Insert into BH103436.ESTADO (UF,NOME) values ('SC','Santa Catarina');
Insert into BH103436.ESTADO (UF,NOME) values ('SP','São Paulo');
Insert into BH103436.ESTADO (UF,NOME) values ('SE','Sergipe');
Insert into BH103436.ESTADO (UF,NOME) values ('TO','Tocantins');
